version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: snap
      POSTGRES_PASSWORD: snap123
      POSTGRES_DB: snapvault
    ports:
      - "5432:5432"

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
    restart: always
    
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend